= SmartERP
:lang: zh_CN
:pdf-themesdir: themes
:pdf-theme:zh_CN

== 1.项目描述
=== 1.1 项目目的
SmartERP旨在为企业提供一个智能的企业资源规划系统，通过集成管理、自动化流程和数据分析，提升企业的运营效率和决策质量。

=== 1.2 项目背景
随着企业规模的扩大和业务复杂性的增加，传统ERP系统已无法满足现代企业的需求。SmartERP应运而生，利用最新的技术，为企业提供更加灵活、智能的解决方案。

=== 1.3 项目范围
SmartERP将涵盖财务、采购、库存、销售、人力资源等多个业务模块，为企业提供全方位的管理支持。

== 2.技术栈

=== 2.1 前端技术
* React: 用于构建用户界面的JavaScript库。
* Material-UI (MUI): React的组件库，提供丰富的UI组件。

=== 2.2 后端技术

* Java: 项目的后端编程语言。
* Spring Boot: 用于简化Spring应用的初始搭建以及开发过程的框架。
* Spring Security：用于实现安全认证和授权
* Hibernate: 作为ORM工具，Hibernate将Java对象映射到数据库表，简化了数据持久化过程
* Spring Data JPA: 与Hibernate结合使用提供简洁的数据访问层实现。
* Spring WebSocket: 用于实现实时通信，支持聊天工具等功能的

=== 2.3 数据库

* MySQL/PostgreSQL: 关系型数据库，用于存储结构化数据。

=== 2.3.1 基本数据结构

[source,sql]
----
create table TAB_USER_LOGIN(
    ID int primary key,
    USERNAME varchar(255) not null ,
    PASSWORD varchar(255) not null,
    USER_INFO_ID int,
)

create table TAB_USER_TEAM (
        USER_ID integer not null,
        TEAM_ID integer not null
    )

create table TAB_TEAM(
    ID int primary key,
    TEAM_NAME varchar(255) not null,
    TEAN_TYPE varchar(255)
)

create table TAB_PERSONNEL (
        ID integer generated by default as identity,
        AVATAR_URL varchar(255),
        EMAIL varchar(255),
        PHONE varchar(255),
        REAL_NAME varchar(255),
        ROBOT boolean,
        USER_LOGIN_ID integer,
        primary key (id)
    )
----

=== 2.4 其他工具和库

== 3.项目架构

=== 3.1 系统架构图
=== 3.2 前后端分离架构
=== 3.3 数据流和控制流
数据流：采用RESTfull API进行前后端数据交互，使用JSON格式进行数据传输。
控制流：前端发送请求到后端API，后端处理请求并返回响应，前端根据响应更新UI。

== 4.关键功能

=== 4.1 功能列表
- dashboard
- 人员管理
- 财务管理
- 模板管理
- 许可证管理
- 聊天工具

=== 4.1.1 Dashboard
展示APP基本情况
APP安装地区等信息

分析
每周销售、新用户、采购订单、消息
当前访问、网站访问

=== 4.1.1 用户管理
人员信息管理是OA系统的最基本的信息功能，人员是系统的底座。该功能主要涉及到的类有~PersonnelController.java~
该类提供功能控制。系统会为提供表格列表查看、HR添加、邀请新员工添加、离职和生成劳动合同等

=== 4.1.4 模板管理
系统提供法律模板、比如收据模板、劳动合同、商业合作以及购买合同等。
以下是JPA定义
[source,java]
----
@Entity
@Table(name = "TAB_TEMPLATE")
public class TemplateEntity extends BasicEntity {

}
----

==== 4.1.4 聊天工具
聊天工具魔模块旨在提供企业内部和客服的沟通平台，支持实时信息传递、文件功共享和AI聊天功能。该模块将集成LLM模型以提供智能化沟通体验。

功能特性：
实现消息传递：支持文本、图片、视频和文件传输。
一对一或群聊：用户可以创建私人聊天或群组进行团队协作
历史消息记录：所有聊天记录都将被保存，方便用户随时查阅
集成通知？

AI聊天功能：
SmartAssist：提供提供名为SmartAssist的LLM智能AI助手，用户可以直接与AI助手进行交互，获取即使帮助和信息。

===== 4.1.4.1 技术实现：
前端：使
后端：后端提供了REST API接口，核心接口分别 `POST:/chat/message` `GET:/chat/`

===== 4.1.4.2 数据库设计结构
[source,sql]
----
create table TAB_CHAT_MESSAGE(
    ID INT PRIMARY KEY,
    CONTENT TEXT NOT NULL,
    SEND_TIME DATETIME NOT NULL,
    MESSAGE_TYPE ENUM('TEXT','IMAGE','FILE') NOT NULL
);
----
聊天会话列表，创建会话名称默认是对方名字
[source,sql]
----
create table TAB_CONVERSATION(
    ID INT PRIMARY KEY,
    CONVERSATION_NAME VARBINARY(255) NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    LAST_ACTIVE_TIME DATETIME NOT NULL
);

create TABLE TAB_CONVERSATION_PERSONNEL_PARTICIPATION (
    ID int primary key ,
    PERSONNEL_ID INT NOT NULL,
    CONVERSATION_ID INT NOT NULL,
)
----

=== 4.2 核心业务流程
=== 4.3 特殊功能需求
- SmartERP提供申请免费延长许可证的功能，允许用户在许可证到期前申请延长试用期或订阅期。如果企业用户在购买ERP系统一年后，即一年许可证接近到期时遇到临时经济困难，可以申请免费延长1年或半年的许可证。

== 5. 模块划分

=== 5.1 前端模块
=== 5.2 后端模块

== 6. 开发环境
=== 6.1 硬件要求
没有要求，为了良好的开发体验建议内存16GB RAM更高和SSD硬盘，未来会集成相关供应商和Docket等功能最好提供网络支持。

=== 6.2 软件要求
- 操作系统：Windows/Linux/MacOS
- JDK：17版本或更高版本
- Node.js:最新版本就可以

=== 6.3 开发工具
- IDE:Intellij IDEA/Eclipse等都可以，只要支持Maven项目结构
- 版本控制:Git

== 7. 部署方式
=== 7.1 本地部署
=== 7.2 生产环境部署
=== 7.3 持续集成和持续部署（CI/CD）

== 8. 安全性和性能
=== 8.1 安全措施
=== 8.2 防止作弊的措施
- 财务信息验证: 实施严格的财务信息验证流程，包括与第三方财务系统或银行进行核对。
- 人工审核: 由专业的财务人员对提交的财务信息进行人工审核，以识别潜在的虚假信息。
- 交叉验证: 通过交叉验证用户提供的财务报表和其他业务数据，如销售记录、采购订单等，来确保信息的准确性。
- 定期审计: 定期对已批准的许可证延长案例进行审计，以确保合规性。
- 智能分析: 使用数据分析工具来检测异常模式或潜在的欺诈行为。

=== 8.2 性能优化

== 9. 测试策略
=== 9.1 单元测试
=== 9.2 集成测试
=== 9.3 系统测试
=== 9.4 性能测试

== 10. 文档和代码标准
=== 10.1 代码规范
=== 10.2 文档规范
- AsciiDoc (adoc): 用于编写项目文档的轻量级标记语言。
- 文档结构: 保持一致的章节和子章节结构。
- 图片和图表: 使用明确的文件名和适当的标签进行引用。

=== 10.3 版本控制
- Git: 用于版本控制的分布式系统。

== 11. 项目管理和协作
=== 11.1 团队结构
=== 11.2 通信工具
=== 11.3 问题跟踪和任务管理

== 12. 里程碑和交付物
=== 12.1 里程碑计划
=== 12.2 交付物列表

== 13. 附录
=== 13.1 术语表
=== 13.2 参考文献

== 项目结构

当前项目结构：

* `frontend` 是页面React前端资源
** `views`
* `src` 是java的源代码